name: lanes_planes_flutter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: packages/core
  localization:
    path: packages/localization

  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  equatable: ^2.0.7
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  go_router: ^16.2.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.3.3
  freezed: ^3.2.0
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - packages/core/assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
